AllCops:
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Max: 200

Style/AlignParameters:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - Rakefile
  
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
